# Jacobi Transformation of a Symmetric Matrix
### Christina Lee
### Category: Numerics
#### based on Numerical Recipes in C++, Sec 11.1

So you want to diagonalize a matrix, do you?
Well, if you have a tiny symmetric matrix, you REALLY want to write up the algorithm by hand, and don't want to spend much time trying to understand the algorithm, then you have come to the right place. 

Otherwise, use LAPACK/BLAS to call a highly optimized routine that can work extremely quickly on large matrices.  Julia has those libraries built in already.  Even if you do call those matrices, you can make them work better by understanding what's going on underneath the hood, which is why we are going through this now.

Start with a base Rotation Matrix of the Form
\begin{equation}
    P_{pq} =
    \begin{pmatrix}
           1& &  &  && && 0\\
           & \ddots &&&&  & \\
            && c & \cdots & s && \\
                &&\vdots& 1 & \vdots &&\\
               && -s & \cdots & c && \\
               &&&&& \ddots & \\
               0&&& &  && 1 
    \end{pmatrix}
\end{equation}

From our starting arbitrary symmetric A,
\begin{equation}
A^{T} = A
\end{equation}
we will run a series of transformations,
\begin{equation}
A^{\prime}= P^{T}_{pq} \cdot A \cdot P_{pq}
\end{equation}
where each iteration brings A closer to diagonal form.  Thus in our implementing our algorithm, we need to determine two things
<ul>
<li> The values of c and s
<li> The pattern of sweeping p and q
</ul>
And in the end we will need to finally determine if this actually converges, and if has any sort of efficiency.

So lets expand one transformation, and we if we can solve for $c$ and $s$.

\begin{align}
a^{\prime}_{rp} & = c a_{rp} - s a_{rq} \\
a^{\prime}_{rq} & = c a_{rq} + s a_{rp} \\ 
a^{\prime}_{pp} & = c^2 a_{pp} + s^2 a_{qq} -2 sc a_{pq} \\
a^{\prime}_{qq} & = s^2 a_{qq} + c^2 a_{qq} + 2sc a_{pq} \\
a^{\prime}_{pq} & = \left( c^2-s^2 \right) a_{pq} + sc \left(a_{pq} - a_{qq} \right)
\end{align}

## Determining $s$ and $c$
Given we specifically want $a^{\prime}_{pq}$ to be zero, we re-arrange the last equation,
\begin{equation}
        \frac{c^2-s^2}{2 sc} = \frac{a_{pq}-a_{qq}}{2 a_{pq}} =\theta
\end{equation}
At first glance, this equation might not look easier to solve for $s$ or $c$.  Second either. We define a new parameter $t = s/c$, which now makes the equation,
\begin{equation}
\frac{1-t^2}{2 t} = \theta \;\;\;\; \implies \;\;\; t^2 -2 \theta t -1=0,
\end{equation}
now quite easily solvable by our friendly quadratic formula.  Though the book does recommend using form that pulls out smaller root through
\begin{equation}
t=\frac{\text{sgn}(\theta)}{|\theta| + \sqrt{\theta^2 + 1} }.
\end{equation}
Then reverse solve back to
\begin{align}
c&=\frac{1}{\sqrt{t^2+1}}\\
s&=tc
\end{align}

Though we could use the expressions above, if we simplify them with our new expressions for $c$ and $s$ analytically, we reduce computational load and round off error. These new expressions are
\begin{align}
a^{\prime}_{pq} & = 0\\
a^{\prime}_{qq} & = a_{qq} + t a_{qp} \\
a^{\prime}_{pp} &= a_{pp} - t a_{pq} \\
a^{\prime}_{rp} &= a_{rp} - s \left( a_{rq} +\tau a_{rp} \right) \\
a^{\prime}_{rq} &= a_{rq} + s \left( a_{rp} -\tau a_{rq} \right)
\end{align}
with the new variable
\begin{equation}
\tau = \frac{s}{1+c}
\end{equation}

## Convergence

The sum of the squares of the off diagonal elements (choosen in either upper or lower triagnles arbitrarily)
\begin{equation}
S=\sum\limits_{r < s} |a_{rs}|^2
\end{equation}

## Eigenvectors

By forming a product of every rotation matrix, we also come to approximate the matrix $V$ where 
\begin{equation}
D = V^{T} \cdot A \cdot V
\end{equation}
and $D$ is the diagonal form of $A$.  $V$ is computed through itereative computation
\begin{align}
V^{\prime} & = V \cdot P_i \\
v^{\prime}_{rs} &= v_{rs} \\
v^{\prime}_{rp} &= c v_{rp} - s v_{rq} \\
v^{\prime}_{rq} &= s v_{rp} + c v_{rq} 
\end{align}

### Enough with the talking! LETS COMPUTE STUFF

In [3]:
# First, Lets make our nice, helpful functions

## A function to look at the convergence
function convergence(A::Array)
    num=0.0
    l=size(A)[1]
    for ii in 1:(l-1)
        for jj in (ii+1):l ## just looking at the lower triangle
            num+=A[ii,jj]^2
            #println(ii,' ',jj,' ',num,' ',A[ii,jj])
        end
    end
    return num
end

convergence (generic function with 1 method)

In [4]:
# This makes a matrix easier to look at when its filled 
# with 1.043848974e-12 everywhere
function roundmatrix(A::Array,rtol::Real)
    Ap=copy(A)
    for ii in 1:length(A)
        if abs(Ap[ii])<rtol 
            Ap[ii]=0
        end
    end
    return Ap;
end

roundmatrix (generic function with 1 method)

In [5]:
## Here we create a random symmetric matrix
function makeA(n::Int)
    A=randn(n,n);
    for ii in 1:n
        A[ii,1:ii]=transpose(A[1:ii,ii]) 
    end
    V=eye(n) #initializing the orthogonal transformation
    return A,copy(A),V
end
## One A returned will be stored to compare initial and final

makeA (generic function with 1 method)

In [6]:
#Now on to the Rotations!

# We don't always want to compute the eigenvectors, so those are in the 
# optional entries slot. 
# Both tell the function to compute the vectors with computeV=true
# and input the V=V after the semicolon.

function Rotate(A::Array,p::Int,q::Int; computeV=false, V::Array=eye(1))
    θ=(A[q,q]-A[p,p])/(2*A[p,q]);
    t=sign(θ)/(abs(θ)+sqrt(θ^2+1));
    
    c=1/sqrt(t^2+1)
    s=t*c
    τ=s/(1+c)
    
    l=size(A)[1]
    Ap=copy(A[:,p])
    Aq=copy(A[:,q])
    for r in 1:l
        A[r,p]=Ap[r]-s*(Aq[r]+τ*Ap[r]) 
        A[r,q]=Aq[r]+s*(Ap[r]-τ*Aq[r])
        
        A[p,r]=A[r,p]
        A[q,r]=A[r,q]
    end
    A[p,q]=0
    A[q,p]=0
    A[p,p]=Ap[p]-t*Aq[p]
    A[q,q]=Aq[q]+t*Aq[p]
    
    if computeV==true
        Vp=copy(V[:,p])
        Vq=copy(V[:,q])    
        for r in 1:l   
            V[r,p]=c*Vp[r]-s*Vq[r]
            V[r,q]=s*Vp[r]+c*Vq[r]
        end
        return A,V
    else
        return A;
    end
end

Rotate (generic function with 1 method)

In [7]:
# This function performs one sweep
function Sweep(A;compV=false,V=eye(1))
    n=size(A)[1]
    for ii in 2:n
        for jj in 1:(ii-1) ## Just over one triangle
            if compV==false
                A=Rotate(A,ii,jj)
            else
                A,V=Rotate(A,ii,jj;computeV=true,V=V);
            end
        end
    end
    
    if compV==false
        return A
    else
        return A,V
    end 
end

Sweep (generic function with 1 method)

In [8]:
A,A0,V=makeA(5);

In [9]:
## keep evaluating for a couple iterations
## watch how it changes
A,V=Sweep(A;compV=true,V=V);
roundmatrix(A,1e-10),A,V,convergence(A)

(
5x5 Array{Float64,2}:
  1.4948     0.116921    1.02763    -0.434912   -0.188183 
  0.116921  -2.84648     0.0963164   0.282086    0.292827 
  1.02763    0.0963164   0.0260007  -0.0918717  -0.0863438
 -0.434912   0.282086   -0.0918717  -2.50395     0.0      
 -0.188183   0.292827   -0.0863438   0.0        -1.29901  ,

5x5 Array{Float64,2}:
  1.4948     0.116921    1.02763    -0.434912   -0.188183 
  0.116921  -2.84648     0.0963164   0.282086    0.292827 
  1.02763    0.0963164   0.0260007  -0.0918717  -0.0863438
 -0.434912   0.282086   -0.0918717  -2.50395     0.0      
 -0.188183   0.292827   -0.0863438   0.0        -1.29901  ,

5x5 Array{Float64,2}:
  0.437993    0.0130328    0.325224    0.115869   0.829937 
  0.0146638   0.849826    -0.0800861   0.517046  -0.0618865
 -0.383632   -0.00380988   0.897765    0.136057  -0.16828  
 -0.437074   -0.430791    -0.251751    0.709822   0.236981 
 -0.685376    0.303365    -0.135846   -0.443711   0.472119 ,

1.4847562147413709)

In [10]:
## Compare the Optimized LAPLACK routine to your results
eig(A0)

([-3.0692662458854665,-2.3884515551279404,-1.2546686989796698,-0.49477842953790496,2.0785140022018687],
5x5 Array{Float64,2}:
 -0.207535   -0.0391866  -0.846272  -0.115829    -0.475185 
  0.488515   -0.863584   -0.111218   0.0283255    0.0490272
 -0.0373319  -0.0801275   0.181727  -0.977372    -0.0624916
 -0.713881   -0.352832   -0.138244  -0.00715952   0.588829 
  0.455261    0.348963   -0.468314  -0.174568     0.648976 )

In [12]:
## A good check to make sure V is an orthonomal transformation
roundmatrix(V*A*transpose(V)-A0,1e-12)

5x5 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [13]:
# How long does it take to make a Sweep?
# How much memory will the computation take?
# This is dependent on how large the matrix is
A,A0,V=makeA(10);
@time Sweep(A);
A,A0,V=makeA(20);
@time Sweep(A);
A,A0,V=makeA(100);
@time Sweep(A);

  0.001878 seconds (1.08 k allocations: 75.580 KB)
  0.000196 seconds (1.33 k allocations: 187.266 KB)
  0.012980 seconds (34.66 k allocations: 17.448 MB, 22.64% gc time)


In addition to time per sweep, we need to know how many sweeps we need to run. So again we run it on a 10x10, 20x20, and 100x100. The efficiency of the algorithm would get a lot worse if we have to sweep the 100x100 a bunch of times.

In [20]:
A10,Ap10,V=makeA(10);
A20,Ap20,V=makeA(20);
A100,Ap100,V=makeA(100);
nsweep=collect(1:7);
conv10=zeros(7)
conv20=zeros(7)
conv100=zeros(7)
for i in nsweep
    A10=Sweep(A10)
    A20=Sweep(A20)
    A100=Sweep(A100)
    conv10[i]=convergence(A10)
    conv20[i]=convergence(A20)
    conv100[i]=convergence(A100)
end

[nsweep conv10/100 conv20/400 conv100/10000 conv20./(4*conv10) conv100./(100*conv10)]

7x6 Array{Float64,2}:
 1.0  0.132261     0.0918583    0.142374        0.69452        1.07646   
 2.0  0.024914     0.0126652    0.0293247       0.508356       1.17704   
 3.0  0.00106589   0.000835482  0.00477146      0.783833       4.47649   
 4.0  9.02829e-8   2.61435e-6   0.000480568    28.9573      5322.91      
 5.0  5.49671e-15  3.15077e-11  1.0185e-5    5732.11           1.85293e9 
 6.0  5.92701e-38  1.49483e-24  1.44118e-8      2.52206e13     2.43155e29
 7.0  7.91672e-88  7.87516e-55  2.16057e-14     9.94751e32     2.72913e73

Well, so we've seen how to do one form of exact diagonalization that works, but doesn't scale very well up to 100x100 matrices.  So stay tuned for the Householder method, hopefully coming up soon.

Until then, happy computing :)